---
# tasks file for pip

- name: installing pip
  yum:
    name: python3-pip
    state: latest

- name: updating pip
  shell:
    cmd: "pip3 install --upgrade pip"

- name: config pip
  command: "{{ item }}"
  with_items:
    - "python3 -m pip config --global set global.index http://158.160.50.122/artifactory"
    - "python3 -m pip config --global set global.index-url http://158.160.50.122/artifactory"
    - "python3 -m pip config --global set global.trusted-host 158.160.50.122"

- name: download pip.conf from remote server
  fetch:
    src: "/etc/pip.conf"
    dest: "/mnt/d/home/esm/B9-proj/data/"

