---
# tasks file for artifactory

- name: create jfrog home dir
  file:
    path: '{{ artifactory_home }}/var/etc/'
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"
    recurse: true

- name: copy artifactory conf file
  copy:
    src: '/mnt/d/home/esm/B9-proj/data/system.yaml'
    dest: '{{ artifactory_home }}/var/etc/'
    owner: "root"
    group: "root"

- name: docker build and run
  shell:
    cmd: "docker run --name artifactory -v {{ artifactory_home }}/var/:/var/opt/jfrog/artifactory -d -p 8081:8081 -p 80:8082 releases-docker.jfrog.io/jfrog/artifactory-pro:latest"
