---
# tasks file for artifactory

- name: create artifactory home dir
  file:
    path: '{{ jfrog_home }}/artifactory/var/'
    state: directory
    mode: '0777'
    owner: "1030"
    group: "1030"
    recurse: true

- name: copy artifactory conf file
  copy:
    src: '/mnt/d/home/esm/B9-proj/data/system.yaml'
    dest: '{{ jfrog_home }}/artifactory/var/etc/'
    mode: '0777'
    owner: "1030"
    group: "1030"

- name: docker build and run
  shell:
    cmd: "docker run --name artifactory -v {{ jfrog_home }}/artifactory/var/:/opt/jfrog/artifactory/var/ -d -p 8081:8081 -p 80:8082 releases-docker.jfrog.io/jfrog/artifactory-pro:latest"
