---
- name: add user to vm1
  hosts: b6_all
  gather_facts: true
  become: true
  become_user: "root"
  become_method: "sudo"

  roles:
    - role: "/home/esm/ansible/playbooks/b6-summary/ansible/roles/users"
